services:
  db:
    hostname: db
    image: pgvector/pgvector:pg16
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_DB=cudeschin
      - POSTGRES_USER=ai
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_HOST_AUTH_METHOD=trust
